version: "3.7"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - sql-server-db
    sql-server-db:
        container_name: sql-server-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "SqlExpress!"
            ACCEPT_EULA: "Y"
        stdin_open: true

